#!/bin/bash

if [ -z $1 ]; then
   echo "This is a service manager writen by DebianLynx"
   echo "it would launch the service automatically when termux start"
   echo "Usage:"
   echo "enable/disable SERVICE_NAME  (enable automatically startup)"
   echo "guide                        (add backgroud service with a few seconds)"
fi

if [ $1 == enable ]; then
  
